import BackToHome from '../components/BackToHome';

export default function TermsPage() {
  return (
    <>
      <BackToHome />
      <div className="container mx-auto px-4 py-16 max-w-4xl">
        <h1 className="text-4xl md:text-5xl font-bold mb-12 text-center text-gray-900 dark:text-white">Terms of Service</h1>
        <div className="prose dark:prose-invert max-w-none">
          <p className="text-sm text-gray-600 dark:text-gray-400 mb-8 italic">Last Updated: April 24, 2025</p>

          <p>Welcome to GitRead, a product of Koyal Labs, LLC ("Koyal Labs," "we," "us," or "our"). GitRead ("Service" or "GitRead") is an AI-powered tool that allows users to generate README files for GitHub repositories by providing a repository link.</p>

          <p>By accessing or using the Service, you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use our Service.</p>

          <h2>1. Use of the Service</h2>
          <p>GitRead is intended to help users generate README documentation for open-source and public GitHub repositories. By using GitRead, you agree that:</p>
          <ul>
            <li>You will only use the Service for lawful purposes.</li>
            <li>You will not use the Service to generate documentation for repositories you do not have the right to access or use.</li>
            <li>You grant Koyal Labs a limited, non-exclusive license to access and process the repositories you provide in order to generate README content.</li>
          </ul>

          <h2>2. Accounts and Authentication</h2>
          <p>To access certain features of GitRead, you may need to create an account or authenticate through GitHub or another provider. You agree to provide accurate and complete information and to keep your credentials secure.</p>

          <h2>3. Payment and Credits</h2>
          <p>GitRead offers a paid plan. For paid services:</p>
          <ul>
            <li>You may purchase usage credits.</li>
            <li>Credits are non-transferable and non-refundable except in specific cases of failed generations (see Section 6).</li>
          </ul>

          <h2>4. Intellectual Property</h2>
          <ul>
            <li>All content generated by GitRead is provided as-is and may incorporate data or language derived from public repository content.</li>
            <li>Koyal Labs retains ownership of the GitRead platform, algorithms, and all associated intellectual property.</li>
            <li>You retain ownership of your GitHub content and are responsible for ensuring that any use of GitRead complies with applicable licenses.</li>
          </ul>

          <h2>5. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use the Service for any unlawful, harmful, or malicious purposes.</li>
            <li>Attempt to reverse-engineer, clone, or misuse GitRead in ways that violate its intended purpose.</li>
            <li>Upload or link to repositories containing sensitive, personal, or illegal content.</li>
          </ul>

          <h2>6. Failed Generations & Refund Policy</h2>
          <p>If you encounter a failed README generation:</p>
          <ul>
            <li>Contact us at <a href="mailto:koyalhq@gmail.com" className="text-purple-600 hover:text-purple-700 transition-colors">koyalhq@gmail.com</a> with your account information and a description of the issue.</li>
            <li>We may, at our discretion, restore any lost credits resulting from failed generations.</li>
            <li><strong>No monetary refunds will be issued</strong>, regardless of the quality or outcome of the generated content.</li>
          </ul>

          <h2>7. Disclaimer of Warranties</h2>
          <p>GitRead is provided on an "as-is" and "as-available" basis. We make no guarantees regarding the quality, accuracy, or fitness of the generated content for any specific purpose.</p>

          <h2>8. Limitation of Liability</h2>
          <p>To the fullest extent permitted by law, Koyal Labs shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including but not limited to loss of data, profits, or reputation.</p>

          <h2>9. Termination</h2>
          <p>We reserve the right to suspend or terminate your access to GitRead at any time for violation of these Terms or for any other reason deemed necessary to protect the integrity of the Service.</p>

          <h2>10. Changes to the Terms</h2>
          <p>We may update these Terms from time to time. We will notify users of material changes, but it is your responsibility to review the Terms periodically.</p>

          <h2>11. Governing Law</h2>
          <p>These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, without regard to its conflict of law principles.</p>

          <h2>12. Contact Us</h2>
          <p>For questions about these Terms or the Service, contact us at:</p>
          <p>Koyal Labs, LLC<br />
          Email: <a href="mailto:koyalhq@gmail.com" className="text-purple-600 hover:text-purple-700 transition-colors">koyalhq@gmail.com</a></p>
        </div>
      </div>
    </>
  );
} 